# Generated by Django 3.2.19 on 2023-12-31 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_adminmanager_coursemanager_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.academy', verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.major', verbose_name='专业'),
        ),
    ]
