# Generated by Django 3.2.19 on 2023-12-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20231231_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='major',
        ),
    ]
