# Generated by Django 3.2.19 on 2024-01-04 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_teacher_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='academy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.academy', verbose_name='学院'),
        ),
    ]
